(package "manage-minor-mode-table"
         "0.1.3"
         "Manage minor-modes in table")

(website-url "https://github.com/jcs-elpa/manage-minor-mode-table")
(keywords "tools" "minor-mode" "manage")

(package-file "manage-minor-mode-table.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "25.1")
(depends-on "manage-minor-mode")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
